### ISSUE TITLE
Sensors do not show any information

### ISSUE THREAD

**Issue by Jolly-Roger82** [heinoldenhuis/home_assistant_area_waste#3]
I've installed the integration and followed every step in the README. 
Configured my postal code (Hoogeveen) and Housenumber in my configuration.yaml and added a standard entity card in my Lovelace. But whatever I do, the sensors don't show any dates or only show "unknown"

![image](https://user-images.githubusercontent.com/45370480/82413473-b19e1580-9a75-11ea-8b83-fda2a5068283.png)

**Comment by JanLankhorst** [comment]
I see a meetup upcoming: Homeassistant users in Hoogeveen..

If you need assistance in getting this working let me know (I am no expert but have been fiddling around with HA for the last 2 years) and have Area_waste running.

**Comment by heinoldenhuis** [comment]
Hello Jolly-Roger82, I will look into this issue and test some postal codes in Hoogeveen later today. I am self living in the surroundings of Emmen, this still works. Keep you posted.

Is the https://www.area-afval.nl/voor-bewoners/afvalkalender/digitale-afvalkalender working for your postalcode and housenumber?
The HA integration is using the same API that is used for this Web application.

**Comment by heinoldenhuis** [comment]
Hello Jolly-Roger82, I have tested some postal codes in Hoogeveen and Area area surroundings.
This seems to be working ok.
On the other hand some adresses filled in for example on https://www.area-afval.nl/voor-bewoners/afvalkalender/digitale-afvalkalender are translated into other housenumbers, for example 4a is translated into 4.
Even if this is already another adres.
The timeschedule is the same for Area.

Could you send me a mail with your postalcode and adres?
I will check if this adres works with the calender en send you the results or config.
Mail adres: heinoldenhuis@gmail.com

**Comment by heinoldenhuis** [comment]
This integration is deprecated. Area Reiniging is added to integration https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer which can also be found in HACS.

If you need help in setting up your config using your postal code I am happy to assist you with the new integration.
